### ISSUE TITLE
Support setup.py

### ISSUE THREAD

**Issue by AlistairB** [deadpendency/deadpendency#18]
This is tricky because there is so much variety in how dependencies are listed in a setup.py file.

**Comment by mdantonio** [comment]
Hello,
just an endorsement for this issue, that would be very useful for me

At the moment I'm unable to use deadpendency on my python projects because I specify dependencies only in setup.py.
I was thinking about some automatic hook (maybe in pre-commit) to produce requirements.txt files from setup.py only to let deadpendency to work, but a direct support for setup.py would be much easier to be integrated.

Can I ask you if there are any news about this possible support?

Thank you!

**Comment by AlistairB** [comment]
Thanks for the feedback! It is very useful to me.

You giving the feedback is enough to push me to do this. Or at least investigate the possibility of supporting a specific subset. In the past I hesitated as it is difficult to know where to draw the line.

A short term fix is to load the `requirements.txt` into your `setup.py`. https://stackoverflow.com/questions/14399534/reference-requirements-txt-for-the-install-requires-kwarg-in-setuptools-setup-py Although, interestingly the second answer argues why you should not do this hehe.

I'll start investigating this next week. Cheers

**Comment by mdantonio** [comment]
Thank you for your quick reply! I will be glad to beta-test any support you will decide to implement

**Comment by AlistairB** [comment]
So I'm thinking about supporting the following:

## Direct inline dependencies

This would be the minimum required. `tests_require` is apparently deprecated, but it wouldn't add much burden to support it.

```python
setup(
    name='example',
    version='0.1.0',
    description='Setting up a python package',
    install_requires=[
        'PyYAML',
        'pandas==0.23.3',
        'numpy>=1.14.5'
    ],
    extras_require={'plotting': ['matplotlib>=2.2.0', 'jupyter']},
    setup_requires=['pytest-runner', 'flake8'],
    tests_require=['pytest']
)
```

## Dependencies passed in as variables

This style is quite popular.

```python
setup_requires = [ "cooldep" ] 

install_requires = [
    "Kivy==1.11.1",
    "Kivy-Garden==0.1.4"
]

extras_require = {
    'test': [
        "pycryptodome",
    ],
    'lint': [
        "flake8==3.8.1",
    ],
    'dev': [
        "bumpversion>=0.5.3,<1",
        "eth-hash>=0.1.0,<1.0.0",
    ],
}

setup(
    name=about['__title__'],
    version=about['__version__'],
    description=about['__description__'],
    install_requires=install_requires,
    extras_require=extras_require,
    setup_requires=setup_requires,
    tests_require=tests_require
)
```

## Others

There is a lot of variation beyond this, but these seem to be the most common.

**Comment by mdantonio** [comment]
Personally, I'm using the first syntax but I will be able to also test the second one with very few modifications.

I agree that there is no need, at least initially, to support all the crazy variations of setup.py syntax!

**Comment by AlistairB** [comment]
@mdantonio This should be done :crossed_fingers: 

I've added support as per my comment. Additionally, I supported specifying dependencies as:

```python
requirements = [
    "Kivy==1.11.1",
    "Kivy-Garden==0.1.4"
]

setup(
    name=about['__title__'],
    install_requires=requirements,
)
```

which also seems fairly common.

Additionally, I note that `setup.py` has git dependencies which I have not added support for. I would, but they seem rare, and I can't find clear information on the formats that are supported. I created https://github.com/deadpendency/deadpendency/issues/35 to track this. I'll probably ignore these until someone request this support.

Anyway, let me know if you have any issues :sweat_smile: (Or if you other feedback for Deadpendency!)

**Comment by AlistairB** [comment]
Hmm I see the failures around having comments in the dependency list. I'll fix it!

**Comment by AlistairB** [comment]
@mdantonio Thanks for your patience. This should be all good now - https://github.com/rapydo/http-api/runs/2503487339

**Comment by mdantonio** [comment]
Thank you, it is working very well!

Just a curiosity, I have a number of Failed To Analyze Repository host is unknown, for example for plumbum

Since deadpendency is unable to retrieve the github page (i guess because it is not linked from the related pypi page) no scan is possible. I have to provide this link by myself (by setting it as additional dependency?) or it is something that can depend/handled from you ?

**Comment by AlistairB** [comment]
Great!

Yes that is right. https://pypi.org/project/plumbum/ does not refer to a repository so deadpendency can't find it. However, you can [specify/override the repository for a specific dependency using additional dependencies](https://deadpendency.com/docs/config#additional-dependencies).

For example, I [modified your deadpendency config](https://github.com/deadpendency/http-api/commit/3d23036622dc8ccd5770dc8d1c62582c19665db9) with `plumbum`, which then loaded it as a git dependency - https://github.com/deadpendency/http-api/runs/2506333431

I'm going to close this issue for now. Let me know if you hit any more roadblocks!

**Comment by mdantonio** [comment]
Thank you
