### ISSUE TITLE
Failure to parse large cabal file in reasonable memory / time

### ISSUE THREAD

**Issue by AlistairB** [deadpendency/deadpendency#19]
https://github.com/recursion-ninja/PCG/blob/master/phylogenetic-component-graph.cabal

Sorry @recursion-ninja . `Cabal` the library is exploding in memory usage when parsing your cabal file. I'm investigating. I can re run the report once I figure out what is going on.

https://github.com/recursion-ninja/PCG/runs/1923266021

**Comment by recursion-ninja** [comment]
Admittedly, this is a *very* big cabal file with *many* build targets and internal libraries. The parsing troubles isn't that surprising. If there is a way I can provide you more information to help with the issue, let me know.

**Comment by AlistairB** [comment]
This should be all fixed. See https://github.com/recursion-ninja/PCG/runs/1923266021 . Thanks for your patience :sweat_smile: 

I thought this might be some bug with `Cabal` 3.4, but it was my mistake and a pretty awesome one. I think I will write a blog post about it, but in short I had a list of test dependencies `[[Dependency]]` which I ultimately wanted to flatten into `[Dependency]`. I did achieve this, but did an inadvertent `sequenceA (testDeps :: [[Dependency]])` along the way. What does this do? Creates a list of all possible permutations of all values of all the lists!

```
ghci> sequenceA [[1,2],[3,4], [5,6]]
[[1,3,5],[1,3,6],[1,4,5],[1,4,6],[2,3,5],[2,3,6],[2,4,5],[2,4,6]]
```

In the case of your cabal file you had enough test dependencies that this would easily consume 4GB and take over 60 seconds whoops!

**Comment by recursion-ninja** [comment]
Absolutely no worries regarding the turn around. You've been a paragon of rectitude. 

Glad I could inadvertently provide a "stress test" input for your product. It was an interesting defect indeed.
