### ISSUE TITLE
Support a more conventional location for `.deadpendency/config.yaml` on GitHub

### ISSUE THREAD

**Issue by webknjaz** [deadpendency/deadpendency#44]
Hi, I'd like to be able to have the config file located at `.github/deadpendency.yaml` per common convention in many GitHub Apps (especially Probot-based ones).

## Why do you want this feature?

Adding a config file or a folder for each and every tool a project may use pollutes the project root directory. GitHub typically advises putting the configs under the `.github/` folder and I think that following this convention would help mitigate this pollution problem by allowing the end-users to keep their repo root dirs clean with only a minimal amount of dirs necessary.

## Acceptance Criteria

Deadpendency is able to consume its configuration from `.github/deadpendency.yaml`.

## Other Comments

N/A

**Comment by AlistairB** [comment]
Thanks for feedback! :heart: 

> GitHub typically advises putting the configs under the .github/ folder

Do you have any docs regarding this?

I would like to follow whatever is considered best practice or recommended by GitHub. My current understand of `.github` is that it is the place for configuring how GitHub itself (or first party apps like dependabot native) works, but not as a general bucket for any app on GitHub.

I used the current style as that is what [dependabot used before it was integrated into github](https://dependabot.com/docs/config-file/#dependabot-config-files) and it seems like a vague convention (more modern than just dumping config files in the root).

Anyway I will spend some time trying to find any advice around this. I will also look at more other 3rd party github apps to see what they are doing. Cheers

**Comment by webknjaz** [comment]
I don't remember if GH itself has such docs but I can say that Dependabot used this convention long before GH acquired them. And many apps do this as well. This is coming from Probot (a JS framework for writing GH Apps that is actively supported by GitHub). One of the places to ask about this would be their Slack (join here https://probot-slackin.herokuapp.com). I think you could explore any app here https://probot.github.io/apps/ and you probably won't see many unconventional config locations.

Here are some of the recommendations they have https://probot.github.io/docs/best-practices/#configuration and my understanding is that the JS/Probot community/ecosystem relies on https://github.com/probot/octokit-plugin-config to work with configs in a standardized way (including the possibility of merging configuration fallbacks from other shared repos).

P.S. I have a framework for writing GitHub Apps in Python and when I try to make some fundamental decisions, I always look at what Probot/Octokit do before reinventing the wheel. That's what I recommend to you too.

**Comment by AlistairB** [comment]
Thanks for the info. I am leaning towards moving it into `.github`. I'll do a bit more analysis and make a call. Cheers.

**Comment by AlistairB** [comment]
I agree this is the most common pattern and it does reduce pollution in the root directory. I have made this change ie. config can be loaded from `.github/deadpendency.yaml`, I have left support for `.deadpendency/config.yaml` for now, but it is no longer the standard location and may be removed in the future.

Thanks again :raised_hands: Feel free to make more suggestions :smile:
