### ISSUE TITLE
Incompatible URLs used when downloading from NuGet.org 

### ISSUE THREAD

**Issue by jcjiang** [deadpendency/deadpendency#45]
Hey there.

I'm a PM on the NuGet.org team and I wanted to reach out 

NuGet.org is migrating towards a new multi-CDN infrastructure: https://github.com/NuGet/Announcements/issues/60

Going forward, not all of our CDN providers will support case insensitive URLs. As a result, nuget.org's V3 API to download packages’ content will only support lowercased package ID and version values, as documented here: https://docs.microsoft.com/en-us/nuget/api/package-base-address-resource

For example:

❌ https://api.nuget.org/v3-flatcontainer/Newtonsoft.Json/13.0.1-Beta1/Newtonsoft.Json.13.0.1-Beta1.nupkg

✔ https://api.nuget.org/v3-flatcontainer/newtonsoft.json/13.0.1-beta1/newtonsoft.json.13.0.1-beta1.nupkg

Recently we received requests with uppercased package ID or versions from a client with user agent “deadpendency@deadpendency.com”. We recommend you update your project to use lowercased package ID and versions when downloading packages’ content using nuget.org’s V3 API.

Feel free to reach out to us at support@nuget.org or on GitHub at https://github.com/NuGet/NuGetGallery/issues if you have any questions or concerns.

Best regards,

NuGet Team

**Comment by AlistairB** [comment]
Thanks for the heads up! I have updated this to always use lower case in new version `0.6.8.12`.
