### ISSUE TITLE
Says Laravel is dead

### ISSUE THREAD

**Issue by jstark518** [deadpendency/deadpendency#49]
## Expected Behavior
No warning

## Current Behavior
laravel/framework – 📖 📦
❌ Last package release over 24 months ago. Last release: 2016-07-20

## Example Of Issue / Steps To Reproduce
No changes to the default config

**Comment by AlistairB** [comment]
Thanks for report! Sorry for the issue :bow: 

Without going into too much detail, most Packagist / PHP packages use pure SemVer for versions, but in the case of `laravel/framework` it was prefixing versions with `v`. I have updated my logic to gracefully handle this scenario for Packagist.

If you hit 'Re-run' it should work now. Optimistically closing, please re-open if you get further issues. Thanks again.
