### ISSUE TITLE
Deadpendency thinks "-r <requirements.txt>" in Python requirements.txt files is a dependency

### ISSUE THREAD

**Issue by fniessink** [deadpendency/deadpendency#50]
## Expected Behavior
We have Python requirements files that include other requirements files with "-r <requirements.txt>". Deadpendency should resolve the inclusion of the other requirements file and proceed normally and not include "-r" as package in the report.

## Current Behavior
Deadpendency seems to work properly, but also shows this in the report:

> Failed To Analyze 😞
> 
> Python
> 
> Package was missing from the registry
> 
> -r 

## Example Of Issue / Steps To Reproduce
Example of issue: https://github.com/ICTU/quality-time/pull/2903/checks?check_run_id=4296945837
Example requirements.txt file: https://github.com/ICTU/quality-time/blob/master/components/collector/requirements-dev.txt

**Comment by AlistairB** [comment]
Thanks for report! Sorry for the issue, I'm surprised I missed this haha :sweat_smile:

Anyway, I'm optimistically closing. Please re-open if you see more issues around this.
