### ISSUE TITLE
Disable per repo

### ISSUE THREAD

**Issue by drazisil** [deadpendency/deadpendency#56]
## Why do you want this feature?

I would like the ability to have DeadPendency ignore a repo, or at least not error if it can't find any dependency manfests. Did I miss this in the manual?

## Acceptance Critera

* Pass dependency check if no dependencies are located.

**Comment by AlistairB** [comment]
Thanks for the issue!

GitHub Apps support installing an application is all your repositories, or in specific ones. I would recommend only installing Deadpendency in repos you want it to run in. If you go to https://github.com/settings/installations, then go into Deadpendency, you can switch it to only install in the specific repositories.

This is not clear in the Deadpendency docs, sorry about that. I'll leave this open until they are updated.

**Comment by AlistairB** [comment]
Thanks, I tried to make it a bit clearer that you can install it on specific repositories in the docs. If you still think having a way to disable or ignore deadpendency not finding dependencies via config, feel free to chime in and we can discuss it further.

**Comment by drazisil** [comment]
@AlistairB I would absolutely still love a way to opt out, even if via the presence of an empty config file.

The use case is, out of say, 100+ repos, only 4 aren't applicable, due to having no dependencies. In this case, needing to manually select all my repos in the app, expect for a certain 4, isn't a sane use of time. Much better, in my opinion, to be able to select all and have deadpendency skip a few.

Otherwise I'll have to keep ignoring issues like https://github.com/drazisil/deno-binarytools/runs/6470158412, which doesn't serve me any value.

**Comment by AlistairB** [comment]
Ah this is a good point thanks. I hadn't considered it from that angle. Ok! I will add some

```yaml
disable: true
```

config setting. Cheers

**Comment by AlistairB** [comment]
Sorry, I've been considering this more and er decided against it.. again..

- The case you put forward makes sense, but I think it is more of a GitHub apps level issue not really a Deadpendency specific issue. ie. How to easily install an App in all repositories but a few. Looking at other popular GitHub apps they do not appear to offer a way to disable the app entirely.
- Deadpendency's pricing model is based on how many repositories it is installed into, so installing and disabling doesn't really make sense.
- Deadpendency is not really the kind of app you want to always apply to all repositories. There are many cases for having repositories without having software dependencies, or even not particularly caring about 'dead' dependencies for toy sort of things. So I consider doing a specific install into certain repositories as a generally better choice.
- Admittedly, even with Deadpendency disabled via config, this still generates some load + cost for the Deadpendency backend for little benefit.

Apologies for the flip flopping :sweat_smile:

**Comment by drazisil** [comment]
You have good arguments, and it is your business and expenses on the line. I respect and agree with you. Thank you for giving it as much thought as you did. 👍
