### ISSUE TITLE
Can deadpendency support Scala

### ISSUE THREAD

**Issue by giacomocavalieri** [deadpendency/deadpendency#57]
It would be useful being able to use Deadpendency in an sbt Scala project.

**Comment by AlistairB** [comment]
Thanks for creating this! Yes agree, I want it to support Scala and sbt.

This will take a bit of time as sbt is a custom format and a bit tricky to support. Also, Scala dependencies are stored in Maven a bit differently to Java (the Scala compiler version is part of the package name). I'll update here when I have a better of idea of when I'll be able to implement this. Rough ETA within 4 months. Cheers

**Comment by AlistairB** [comment]
Hi, I have added initial Scala support. Are you happy to try the Scala support out and let me know how it fares?

I have also highlighted some additional support I could add for sbt. See and highlighted some remaining support with these issues - https://github.com/deadpendency/deadpendency/labels/language%2Fscala Do you have any thoughts as to which of these would be useful to you?

**Comment by AlistairB** [comment]
I'm going to optimistically close this.
