### ISSUE TITLE
Add schema for .deadpendency/config.yaml to schemastore.org

### ISSUE THREAD

**Issue by proinsias** [deadpendency/deadpendency#61]
## Why do you want this feature?

Many IDEs use [schemastore.org](https://www.schemastore.org/) to validate json and yaml files. I personally use [v8r](https://github.com/chris48s/v8r) as well. It would be really useful to have a schema for `.deadpendency/config.yaml`.

There are two ways of providing such a schema:
1. Anybody can add the schema directly to the [schemastore repo](https://github.com/schemastore/schemastore/), or
2. The developer of the utility in question can host the schema and just link to this file in the schemastore repo. 

## Acceptance Criteria

I propose that you host the schema in one of this organization's repo, and then you or I can add it to schemastore.

## Other Comments

Feel free to just close this issue if it's not something of interest to you, or it's not something you think you'll ever get to. I can just submit what I think the schema is myself to scratch this itch.

**Comment by AlistairB** [comment]
:wave: Thanks for the issue, I was not aware of the schema store. I want to add this! Will update once it is done thanks.

BTW, based on https://github.com/deadpendency/deadpendency/issues/44 I moved the default location for the deadpendency config file to `.github/deadpendency.yaml`, although both locations are still supported.

**Comment by proinsias** [comment]
Awesome. I like the new default location. If and when you get to this, can you add the schema for both locations if possible?

**Comment by AlistairB** [comment]
> can you add the schema for both locations if possible?

Good idea! Will do.

**Comment by AlistairB** [comment]
I have added this https://github.com/SchemaStore/schemastore/pull/2532 if you want to check it out?

**Comment by proinsias** [comment]
Great! Done! And thanks again!
